# Intro to NumPy

## What is NumPy?

**NumPy** is a type of Python **library**. Libraries are like collections of functions that are all related to each other in some way. Instead of rewriting a whole bunch of functions for a project, you can **import** a library and call all of its functions. Importing is done like this:

In [1]:
import numpy

Sometimes libraries have long names. In order to make it more convenient to type out, you can use **as** followed by a new name to make things easier, like this:

In [2]:
import numpy as np

Now instead of calling NumPy's functions by using **numpy**, you can just use **np**. 

## NumPy arrays

The biggest part of NumPy that makes it so useful is the NumPy **array**. Arrays are like lists, but more flexible and can be used with NumPy functions (many of which are useful in linear algebra!). Arrays are constructed quite similarly to lists, but using the **array()** function from NumPy. Take a look at how it can be used:

In [3]:
my_array = np.array([0,1,2,3,4,5]) #the brackets [ ] form a list, which is then passed into np.array() to form a NumPy array
print(my_array) #arrays are printed like lists but without the commas

[0 1 2 3 4 5]


Notice how you can call the **array** function (and any other function from a library) by doing **np.** followed by the function name. More generally, you can call a library function by typing the library name plus a dot before the actual function header (library.function()).

A special property of arrays is that they can be more than one-dimensional. Take a look at this one and how it's printed:

In [7]:
two_by_two = np.array([[1,2], [3,4]])
print(two_by_two)

[[1 2]
 [3 4]]


In this case, the NumPy array is **two-dimensional**. The general syntax is that within **np.array()**, you need one set of brackets to constitute the overall array. Within those, you can have multiple "mini" lists that will make up each row. Two-dimensional arrays are often used in linear algebra to represent matrices, and so they can have any number of rows and columns, like these:

In [10]:
matrix_2x3 = np.array([[1,2,3],
                      [4,5,6],])
matrix_3x1 = np.array([[1],
                       [2],
                       [3]])
print(matrix_2x3)
print("\n")
print(matrix_3x1)

[[1 2 3]
 [4 5 6]]


[[1]
 [2]
 [3]]


You can get an array's **shape** by calling the **.shape** attribute on an array, like this:

In [12]:
shape = matrix_2x3.shape
print(shape)

(2, 3)


Notice that this returns a tuple where the first entry is the number of rows and the second is the number of columns.

You can also access specific elements and slices of arrays just like with lists. However, accessing an element in a 2D array requires a row and a column, seperated by a comma:

In [18]:
print(matrix_2x3)
my_element = matrix_2x3[0,1] # gets the element in the first row, second column (remember zero-indexing!!)
print(my_element)

[[1 2 3]
 [4 5 6]]
2


Slicing a 2D array is a little more complicated. You can replace the row or column index with **:** to get that entire row/column. Additionally, using slicing you can access only certain rows or columns, certain elements within a column, etc. When slicing using two indeces, the syntax `[x:y]` is like saying start with the element at index 'x' and grab all the elements **up to but NOT including** the one at index 'y'. Here are a few examples using a 3x3 matrix (try to guess what mystery_matrix is before you run it!):

In [27]:
my_3x3 = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
first_column = my_3x3[:,0] # this slicing can be read as [all rows, 1st column]
print(first_column)
print("\n")
first_row = my_3x3[0,:]    # again, [1st row, all columns]
print(first_row)

print("\n")
mystery_matrix = my_3x3[0:2,0:2]
print(mystery_matrix)

[1 4 7]


[1 2 3]


[[1 2]
 [4 5]]


Some additional matrix tools NumPy provides come in the form of **np.sum()** and **np.max()**. The **sum()** function takes an array as input and, by default, will output the sum of all its elements. If you want the sums of the rows or columns, you can specify **axis=0** or **axis=1** in the function. the **max()** function

In [41]:
array = np.array([[0,0,0], # row sums are 0, 3, and 6
                  [1,1,1], # column sums are 3, 3, and 3
                  [2,2,2]])# total sum is 9

print(np.sum(array))        # total sum
print(np.sum(array,axis=0)) # row sums, notice how it's given as another NumPy array
print(np.sum(array,axis=1)) # column sums

print("\n")
print(np.max(array))        # max element
print(np.max(array, axis=0))# max row
print(np.max(array, axis=1))# max column

9
[3 3 3]
[0 3 6]


2
[2 2 2]
[0 1 2]


There's a lot going on in the code above. Take some time to look at the sum/max functions closely, especially with defining the axis. Play around with different matricies to make sure you understand how exactly the axis variable works.

## Array creation functions

Now, you don't always need to manually type in matrix values. There are a few functions that make generic arrays. Specifically, **np.ones()**, **np.ones_like()**, **np.zeros()**, and **np.eye()**. The **ones()** function takes a tuple representing an array's shape, and the function spits out an array of that shape filled with 1's in every entry, like this:

In [13]:
ones_matrix = np.ones((2, 2)) # The shape is (2,2), so 2 rows and 2 columns. Notice how there are two sets of parentheses.
                              # This is because the tuple is one item, grouped by parentheses. The second set is for the
                              # actual function np.ones().
print(ones_matrix)

[[1. 1.]
 [1. 1.]]


Side note: The entries are 1. and not 1 because the datatype from **np.ones()** by default is a **float**.

A similar function is **np.ones_like()**, but instead of passing in a shape tuple, you pass in another array. The function outputs an array like from **np.ones()** using the shape of the inputted array.

In [15]:
another_ones_matrix = np.ones_like(matrix_2x3)
print(another_ones_matrix)

[[1 1 1]
 [1 1 1]]


Now if **np.ones()** makes a matrix filled with 1's, it isn't to hard to guess what **np.zeros()** does:

In [16]:
zeros_matrix = np.zeros((2,2))
print(zeros_matrix)

[[0. 0.]
 [0. 0.]]


Similarly, **np.zeros_like()** works just like **np.ones_like()**:

In [17]:
another_zeros_matrix = np.zeros_like(matrix_2x3)
print(another_zeros_matrix)

[[0 0 0]
 [0 0 0]]


In linear algebra (and most matrix math), the identity matrix is incredibly important. An easy way to make identity matrices is using the cleverly-named function **np.eye()**. A few quirks: Unlike **np.ones()/zeros()**, you don't pass in a shape tuple. Instead, the rows and columns are explicitly passed in as seperate variables. Furthermore, if the matrix isn't square, it will fill out what it can and leave any leftover rows/columns as full of zeros.

In [26]:
square_identity = np.eye(2,2)
non_square_identity = np.eye(4,3)

print(square_identity)
print("\n")
print(non_square_identity)

[[1. 0.]
 [0. 1.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


## Doing linear algebra with NumPy arrays

Now making arrays is great and all, but NumPy's most important traits for this course revolve around using it for linear algebra. The most basic operations work like you'd think - if two matrices are of the same shape, you can use **+** and **-** to add/subtract them. You can also multiply and divide arrays by scalars (integers and floats both work).

In [31]:
ones = np.ones((2,2))
twos_add = ones + ones
twos_multiply = ones*2

print(twos_add)
print("\n")
print(twos_multiply)

[[2. 2.]
 [2. 2.]]


[[2. 2.]
 [2. 2.]]


Another key operation is matrix multiplication. NumPy provides a quick and easy way to denote this using the **@** symbol. Using this in between two matrices of compatible shapes will multiply them together, like this:

In [32]:
array1 = np.array([[1,2],
                   [3,4]])
array2 = np.array([[5,6],
                   [7,8]])
multiplied_array = array1 @ array2
print(multiplied_array)

[[19 22]
 [43 50]]


In a similar vein, you can get the **transpose** of a matrix/array by calling **.T** on it:

In [35]:
my_array = np.array([[1,1],
                     [0,0]])
print(my_array)
print("\n")
print(my_array.T) #notice the .T, T standing for "Transpose"

[[1 1]
 [0 0]]


[[1 0]
 [1 0]]


There's one more main function to cover here for now, one that's in a part of NumPy dedicated to linear algebra:

In [42]:
import numpy.linalg as la

The above line of code imports a specific part of NumPy under the name **la** so we don't have to type **numpy.linalg** every time. Later in the course you'll do more with this library, but for now there's one function that can be useful for CHECKING ANSWERS (not for just doing your homework - you still have to actually learn this stuff!!!). That function is **la.solve()** and it does what it seems like it would. Passing in two matrices will yield a solution if it exists for the matrix equation.

In [43]:
A = np.array([[1,2],
              [3,4]])
B = np.array([[1],
              [1]])
answer = la.solve(A,B)
print(answer)

[[-1.]
 [ 1.]]


Again - one final note: Do NOT just use this, or any other tool, to just solve your homework. It's important to understand linear algebra by itself and not with the assistance of Python. Programming is a tool to apply your knowledge in a more efficient way, not to replace that knowledge. Good luck with the rest of the course and continue learning more about programming! If you ever need help with a specific function in NumPy or just forgot how it works exactly, go to the documentation [here](https://numpy.org/doc/stable/reference/routines.linalg.html)! Have fun!